### ISSUE TITLE
white arrow on some project folders indicates submodule?

### ISSUE THREAD

**Issue by fbegue** [EliEladElrom/react-tutorials#4]
Hey sorry if this is a silly inquiry, but after cloning the repo and seeing an empty **bubble-chart** folder, a quick Google suggests that that project and a couple others are inaccessible b/c they are in separate modules or something? 

Thanks!

**Comment by EliEladElrom** [comment]
Hey @fbegue, you were correct. These folders contained a git and/or gitmodules I cleaned these and cleared the git cache and now the content is in. Enjoy!
